version: "3.7"
services: 
  my-pomodoro-client:
    image: rolalukasz1992/my-pomodoro-client:0.2.0
    depends_on:
      - my-pomodoro-words
    ports:
      - "3000:3000"
    environment:
      - REACT_APP_BACKEND_URL=http://localhost:8090
  
  my-pomodoro-words:
    image: rolalukasz1992/my-pomodoro-words:0.0.5
    ports: 
      - "8090:8080"